<a href="https://colab.research.google.com/github/klngithubsairam/Research/blob/master/LSTM_Program.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [6]:
# LSTM with Dropout for sequence Binary classification

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
#from keras.datasets import imdb
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout
from keras.layers.embeddings import Embedding
from keras.preprocessing import sequence
# fix random seed for reproducibility
np.random.seed(7)
df=pd.read_csv("/content/gdrive/My Drive/RE_Dataset.csv",delimiter=',')
x_train, x_test = train_test_split(df, test_size=0.5,random_state=12)

x1=x_train[['Send','call','dc','if','mscv','bv','bms']].values
y1 = x_train[['Label']].values
print(x1)
print(x1.shape)
print(y1.shape)

x2=x_test[['Send','call','dc','if','mscv','bv','bms']].values
y2 = x_test[['Label']].values
print(x2)
print(x2.shape)
print(y2.shape)

# create the model
embedding_vecor_length = 32
model = Sequential()
#model.add(Embedding(top_words, embedding_vecor_length, input_length=max_review_length))
model.add(Embedding(7, embedding_vecor_length, input_length=7))
model.add(Dropout(0.2))
model.add(LSTM(100))
model.add(Dropout(0.2))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())
model.fit(x1, y1, epochs=3, batch_size=64)
# Final evaluation of the model
scores = model.evaluate(x2, y2, verbose=0)
print("Accuracy: %.2f%%" % (scores[1]*100))



[[0 0 0 1 2 2 1]
 [0 0 2 0 0 0 0]
 [0 0 0 2 2 2 2]
 [0 0 2 0 0 0 0]
 [0 0 0 0 0 0 0]
 [2 2 0 0 0 0 0]
 [0 0 0 2 2 2 2]
 [0 2 0 0 0 0 0]
 [0 0 0 2 2 2 2]
 [2 2 0 0 0 0 0]
 [2 0 0 0 0 0 0]
 [0 0 2 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0]
 [2 0 0 0 0 0 0]
 [0 0 0 1 2 2 1]
 [0 0 0 0 0 0 0]
 [0 0 0 2 2 2 2]
 [2 0 0 0 0 0 0]
 [2 0 0 0 0 0 0]
 [0 0 0 2 2 2 2]
 [0 0 2 0 0 0 0]
 [0 0 0 2 2 2 0]
 [0 0 0 1 2 2 1]
 [2 2 0 0 0 0 0]
 [0 0 0 2 2 2 2]
 [0 2 0 0 0 0 0]
 [0 0 2 0 0 0 0]
 [0 0 0 2 2 2 2]
 [2 0 0 0 0 0 0]
 [0 0 0 2 2 2 2]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [2 2 0 0 0 0 0]
 [0 0 0 2 2 2 0]
 [2 0 0 0 0 0 0]
 [0 0 0 2 2 2 0]
 [0 0 0 1 2 2 1]
 [0 0 0 0 0 0 0]
 [2 2 0 0 0 0 0]
 [0 0 2 0 0 0 0]
 [0 0 0 1 2 2 1]
 [2 0 0 0 0 0 0]
 [0 0 0 2 2 2 0]
 [0 0 0 2 2 2 2]
 [0 2 0 0 0 0 0]
 [2 2 0 0 0 0 0]
 [0 0 0 2 2 2 2]
 [0 0 0 2 2 2 0]
 [2 2 0 0 0 0 0]
 [0 0 0 2 2 2 0]
 [0 0 0 1 2 2 1]
 [2 2 0 0 0 0 0]
 [2 2 0 0 0 0 0]
 [0 0 0 2 2 2 0]
 [2 0 0 0 0 0 0]
 [2 2 0 0 0 0 0]
 [0 0 0 2 2 2 